### PR TITLE
Change project model from eclipse to maven.

### PR DESCRIPTION
**Pull request by liscju**
Using eclipse project model makes project compilation from
cmd line tedious task. This patch change project model to
maven, which enables generating jar from source just by
invoking 'mvn package'.

Nearly all changes this patch makes deals with moving files,
deleting eclipse files, adding pom and ignoring future target
directories.
There is one change in source code in
InitialSiteVerifier:79:

FilesystemUtils.exportResource("/resources/maven-theme.css")
was changed to
FilesystemUtils.exportResource("/maven-theme.css")

It is changed because in jar generated with maven-assembly-plugin
files all resources are placed in jar on the spot(without any
resource directory etc).

### CODE REVIEW

**Comment by romani** [comment]
@attatrol , please apply this PR, more and more people run into problem to make a jar from your project and use it easily.

**Comment by attatrol** [comment]
Excuse me for hiatus, i'm on vacations and can commit all my time to checkstyle.

**Comment by romani** [comment]
@attatrol , we decided to redo your tool under Checkstyle organization, to avoid personal locks . 
FYI - https://github.com/checkstyle/contribution/issues , please let us know if want to participate.

**Comment by attatrol** [comment]
if you mean that the main repository will be moved to checkstyle/contribution, i understand it, its ok.
so do you need my tool to be refactored to comply with checkstyle requirements? Coding will be quite easy, but i can't imagine how to cover it with tests.

**Comment by romani** [comment]
I did fork from your repo to my personal account.
We decided to a bit rethink your tool, ant try to make it base on XML reports. And Render our own HTML view .
New tool should handle huge reports merge, for now we have OOM Exceptions :( .

> so do you need my tool to be refactored to comply with checkstyle requirements?

It would be awesome if you lead a development of new tool under our guidance in non personal repository. I am not fanatic about quality in "contribution" repo , so we are a bit relaxed. For now I demand new code to follow our code style only, see example - https://github.com/checkstyle/contribution/blob/master/releasenotes-xdoc-builder/pom.xml#L115 .
Easy ability to create jar controlled by CI - https://github.com/checkstyle/contribution/blob/master/.travis.yml#L13

> but i can't imagine how to cover it with tests

it would be good to have some, but we need functionality first.

**Comment by attatrol** [comment]
>New tool should handle huge reports merge, for now we have OOM Exceptions :( .
So SAX or StAX parser should be used because DOM parser will devour memory just as html one used in ahsm?

**Comment by romani** [comment]
yes, and we do not need html as all information should be in XML report file. All links we could generate ourself. We will expect that xml and html reports are generated together by chekcstyle plugin.

**Comment by attatrol** [comment]
@romani,
Is it guaranteed that in checkstyle-result.xml "file" entries order is not volatile for the same set of the input files?

**Comment by attatrol** [comment]
@romani,
[https://github.com/attatrol/XMLDiffGen](url) -- here is a prototype of xml diiference generator, it is written around idea of memory saving:
1. It uses StAX for xml parsing.
2. It uses memory efficient structures, such as TreeMap instead of usual HashMap.
3. Assuming that file order in checkstyle-result.xml for different sequential runs of the checkstyle over the same data is the same or differs slightly, i realized eager xml data comparison: 2 parsers read pieces of xml in rotation, try to save parsed data into one map and comparison is executed on collision.
4. JSoup is discarded for html generation, in view of overall html structure simplicity, i desided to form html strings manually and stream them directly to file.

What is done: it works and generates reports, without beauty and summary.

What is not:
1. Multiple checkouts.
2. xdoc and xref generator, this is the toughest challenge, as i understand, checkstyle uses JXR maven plugin for this, and it'll take a couple of days due to my complete inexpirience with maven.
3. html generation is very rudimentary currently, and i need "our own HTML view" for continuation.
4. xml validation against scheme, do we need it? Do you have one?

**Comment by romani** [comment]
ok, looks like are really interested in making this tool ... 

lets switch all discussions to https://github.com/checkstyle/contribution/issues/50 and other issues in organization repository.

please make a PR with initial implementation to our repo to folder "patch-diff-report-tool", and lets discuss implementation details there.

I will answer all your questions on our side.

thanks a lot for desire to help us keep development process under control and quality with ease.

**Pull request merged**
